name: first workflow
on: workflow_dispatch
jobs:
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: first setp
        run: echo "hello world"
      - name: second step
        run: echo "done! goodby"
        
